// DataEN.swift — English memories + letters.

import Foundation

let enMemories: [Memory] = [
  .init(id: "m01", year: 2022, date: "9 June 2022",       sortKey: "2022-06-09", chapterId: "beginning",
        title: "Day one", placeId: "cafe", peopleIds: ["you"], tags: ["firsts","anniversary"],
        body: "I won't pretend I remember every detail. But I remember thinking — this person is going to be in my life for a long time. I didn't know why. I just knew.",
        favorite: true),
  .init(id: "m02", year: 2022, date: "June 2022",         sortKey: "2022-06-15", chapterId: "beginning",
        title: "Three days of messages", placeId: "home", peopleIds: ["you"], tags: ["firsts"],
        body: "We typed too fast and slept too little. I checked the chat between meetings. Once, between sentences. You sent a voice note at 1 AM and I played it four times before answering.",
        favorite: false),
  .init(id: "m03", year: 2022, date: "July 2022",         sortKey: "2022-07-12", chapterId: "beginning",
        title: "Coffee, dinner, the long way home", placeId: "cafe", peopleIds: ["you"], tags: ["firsts","dates"],
        body: "We sat in that café until they wiped the next table around us. Then we ate dinner. Then we walked. You said you weren't tired. I wasn't either. We made the city smaller that night.",
        favorite: true),
  .init(id: "m04", year: 2022, date: "August 2022",       sortKey: "2022-08-20", chapterId: "beginning",
        title: "I said it first", placeId: "home", peopleIds: ["you"], tags: ["firsts"],
        body: "It came out before I could decide whether to say it. You laughed — not at me, with relief — and said it back. I have never been more glad to have failed to keep something in.",
        favorite: false),
  .init(id: "m05", year: 2022, date: "17 September 2022", sortKey: "2022-09-17", chapterId: "falling",
        title: "100 days", placeId: "home", peopleIds: ["you"], tags: ["milestones"],
        body: "I counted, secretly. You counted out loud. We bought a small cake from the bakery on the corner and ate it from the box, with two spoons, on the kitchen floor.",
        favorite: false),
  .init(id: "m06", year: 2022, date: "November 2022",     sortKey: "2022-11-04", chapterId: "falling",
        title: "Caught in the rain", placeId: "home", peopleIds: ["you"], tags: ["ordinary"],
        body: "We ducked under an awning and waited. Twenty minutes. Maybe more. You leaned your head on my shoulder and I think that was the first time I felt completely calm.",
        favorite: true),
  .init(id: "m07", year: 2022, date: "31 December 2022",  sortKey: "2022-12-31", chapterId: "falling",
        title: "Our first new year", placeId: "home", peopleIds: ["you"], tags: ["milestones"],
        body: "Fireworks too loud to hear each other. So you wrote it on my palm with your finger: next year. I knew what you meant. I closed my hand to keep it.",
        favorite: false),
  .init(id: "m08", year: 2023, date: "14 February 2023",  sortKey: "2023-02-14", chapterId: "falling",
        title: "Sick on Valentine's", placeId: "home", peopleIds: ["you"], tags: ["ordinary","milestones"],
        body: "You had a fever of 38.5. I bought soup and the wrong medicine and we watched the same movie twice. You said it was the best Valentine's yet. I think you meant it.",
        favorite: false),
  .init(id: "m09", year: 2023, date: "April 2023",        sortKey: "2023-04-22", chapterId: "falling",
        title: "Đà Lạt", placeId: "dalat", peopleIds: ["you"], tags: ["travel","firsts"],
        body: "Pines and mist. You wore my jacket because you forgot yours. We rode a borrowed scooter slowly, badly. A dog followed us for a block and you wanted to take it home. I almost said yes.",
        favorite: true),
  .init(id: "m10", year: 2023, date: "9 June 2023",       sortKey: "2023-06-09", chapterId: "building",
        title: "One year", placeId: "home", peopleIds: ["you"], tags: ["anniversary","milestones"],
        body: "Year one. We made a list of everything we'd done — small things, mostly. The list was longer than I expected. You added \"and we're still here,\" at the bottom, and underlined it.",
        favorite: true),
  .init(id: "m11", year: 2023, date: "September 2023",    sortKey: "2023-09-10", chapterId: "building",
        title: "Dinner at your parents'", placeId: "parents", peopleIds: ["you","yourmom","yourdad"], tags: ["family","firsts"],
        body: "Your mom kept refilling my bowl. Your dad asked about my work and actually listened to the answers. On the way home you said, \"I think they liked you,\" and I almost cried in the back of the cab.",
        favorite: false),
  .init(id: "m12", year: 2023, date: "December 2023",     sortKey: "2023-12-08", chapterId: "building",
        title: "Two keys", placeId: "apt", peopleIds: ["you"], tags: ["home","milestones"],
        body: "Two keys. One for me. The kitchen still smelled like paint when we ate the first dinner there, sitting on the floor because the table hadn't arrived yet. We were so tired. We were so happy.",
        favorite: false),
  .init(id: "m13", year: 2024, date: "April 2024",        sortKey: "2024-04-03", chapterId: "building",
        title: "The fight I'd rather forget", placeId: "apt", peopleIds: ["you"], tags: ["hard"],
        body: "I won't write it all down. Only this: we figured it out. It took three days and a lot of staring at the ceiling. We were not the same after. We were better.",
        favorite: false),
  .init(id: "m14", year: 2024, date: "9 June 2024",       sortKey: "2024-06-09", chapterId: "staying",
        title: "Two years", placeId: "home", peopleIds: ["you"], tags: ["anniversary","milestones"],
        body: "You said \"we're old now.\" I said \"we're just starting.\" Both true. We bought flowers for ourselves. They lasted nine days.",
        favorite: false),
  .init(id: "m15", year: 2024, date: "October 2024",      sortKey: "2024-10-14", chapterId: "staying",
        title: "Hội An, lanterns", placeId: "hoian", peopleIds: ["you"], tags: ["travel"],
        body: "Lanterns on the river. You bought one and lit it badly. We watched it drift maybe ten meters and then sink. We laughed until we couldn't.",
        favorite: true),
  .init(id: "m16", year: 2025, date: "February 2025",     sortKey: "2025-02-09", chapterId: "staying",
        title: "The quiet weeks", placeId: "apt", peopleIds: ["you"], tags: ["hard"],
        body: "Work was hard. You were tired. I made too much coffee and not enough conversation. You came home one Friday and said \"I missed you\" and we started again. That's the whole entry.",
        favorite: false),
  .init(id: "m17", year: 2025, date: "9 June 2025",       sortKey: "2025-06-09", chapterId: "now",
        title: "Three years", placeId: "cafe", peopleIds: ["you"], tags: ["anniversary","milestones"],
        body: "We didn't do anything special. We went to the same café. We ordered the same coffee. We sat where we sat the first time and didn't have to say much. Three years and we still tell each other things we haven't told anyone.",
        favorite: true),
  .init(id: "m18", year: 2025, date: "December 2025",     sortKey: "2025-12-20", chapterId: "now",
        title: "Winter habits", placeId: "apt", peopleIds: ["you"], tags: ["ordinary"],
        body: "Two mugs in the sink every morning. Your slippers by the door. The way the light comes through the kitchen window at 4 PM and lands on the same square of floor. None of this is interesting. All of this is everything.",
        favorite: false),
  .init(id: "m19", year: 2026, date: "April 2026",        sortKey: "2026-04-11", chapterId: "now",
        title: "Almost four", placeId: "home", peopleIds: ["you","friend"], tags: ["milestones"],
        body: "We talked about the future like it was a real place we could go. We didn't decide anything. We didn't need to. Later, my oldest friend asked how it's going. I said: still good. Still surprising. Still good.",
        favorite: false),
  .init(id: "m20", year: 2026, date: "Today",             sortKey: "2026-05-24", chapterId: "now",
        title: "Today", placeId: "apt", peopleIds: ["you"], tags: ["ordinary"],
        body: "You're in the next room. I can hear you typing. I'm writing this so I remember — not the big things, the small ones. The sound of you, just now, in the next room.",
        favorite: true),
]

let enLetters: [Letter] = [
  .init(id: "l01", date: "8 July 2022", occasion: "one month",
        salutation: "My dear you,",
        body: "Thirty days. I keep thinking that's nothing — and also that it's the longest I've felt like myself in a long time.\n\nYou make me slower in the good way. I noticed the trees on my walk this morning. I noticed the light. I noticed that I am happy in a way I had stopped expecting.\n\nI don't have a question. I don't have a point. I just wanted to write it down so that later, when life gets loud, I can come back and remember that it started this quietly.",
        signature: "Yours,", signedName: "me"),
  .init(id: "l02", date: "25 December 2022", occasion: "our first Christmas",
        salutation: "To the warmest room in the house,",
        body: "Six months. The tree is leaning slightly to the left. You set it up. I have been told not to fix it.\n\nYou made me a small thing today that you said wasn't a big deal and obviously it is. I am keeping it forever, in case that wasn't clear.\n\nIf I ever forget to tell you out loud: thank you for being patient with me. Thank you for not minding that I take a long time to say what I mean. Thank you for waiting.",
        signature: "Always,", signedName: "me"),
  .init(id: "l03", date: "9 June 2023", occasion: "year one",
        salutation: "For our first year,",
        body: "I made a list this morning of all the small things — your laugh when you're surprised, the way you read menus out loud, the bad jokes you commit to. The list was longer than I expected.\n\nI thought a year would feel like a milestone. Instead it feels like the beginning of something I'd like to keep doing for as long as I can.\n\nI'm not very good at remembering to say important things on the day they're important. So I'm saying it now, on every day, in writing: I love you. Year one. Many more, please.",
        signature: "All of me,", signedName: "me"),
  .init(id: "l04", date: "6 April 2024", occasion: "after a hard week",
        salutation: "You,",
        body: "I've been trying to write this for two days. I keep starting and stopping.\n\nHere's what I want to say: I am sorry. I am also proud of us. We didn't pretend it didn't happen. We didn't pretend we didn't mean it. We sat in it and we figured it out.\n\nI love you more after than before. That surprises me. I hope it doesn't surprise you.",
        signature: "Yours, even tired,", signedName: "me"),
  .init(id: "l05", date: "12 January 2025", occasion: "a quiet Sunday",
        salutation: "On a quiet morning,",
        body: "Nothing happened today.\n\nYou slept in. I made coffee badly and brought you a cup anyway. You squinted at the light and said good morning in the voice you only use first thing.\n\nI am writing this because there will be days I forget what ordinary feels like, and I want to remember that ordinary, with you, is the thing I want most.",
        signature: "Always your morning,", signedName: "me"),
  .init(id: "l06", date: "9 June 2025", occasion: "year three",
        salutation: "Three years in,",
        body: "We went to the same café. You wore the wrong shoes for the rain and didn't care. We sat for a long time without saying much.\n\nI know what I have. I'm not done being surprised by it.\n\nHere is the truth at three years: most of the work is just showing up, and most of the joy is, too. You show up. I am trying to. Year four is going to be the best one yet, because I am going to mean it more.",
        signature: "Yours, on purpose,", signedName: "me"),
]
