// DataFR.swift — French memories + letters.

import Foundation

let frMemories: [Memory] = [
  .init(id: "m01", year: 2022, date: "9 juin 2022",       sortKey: "2022-06-09", chapterId: "beginning",
        title: "Jour un", placeId: "cafe", peopleIds: ["you"], tags: ["premières fois","anniversaire"],
        body: "Je ne prétendrai pas me souvenir de chaque détail. Mais je me souviens d'avoir pensé — cette personne va faire partie de ma vie pour longtemps. Je ne savais pas pourquoi. Je le savais, c'est tout.",
        favorite: true),
  .init(id: "m02", year: 2022, date: "Juin 2022",         sortKey: "2022-06-15", chapterId: "beginning",
        title: "Trois jours de messages", placeId: "home", peopleIds: ["you"], tags: ["premières fois"],
        body: "On tapait trop vite et on dormait trop peu. Je vérifiais le chat entre les réunions. Une fois, entre deux phrases. Tu as envoyé un mémo vocal à 1 h du matin et je l'ai écouté quatre fois avant de répondre.",
        favorite: false),
  .init(id: "m03", year: 2022, date: "Juillet 2022",      sortKey: "2022-07-12", chapterId: "beginning",
        title: "Café, dîner, le long chemin du retour", placeId: "cafe", peopleIds: ["you"], tags: ["premières fois","rendez-vous"],
        body: "On est restés dans ce café jusqu'à ce qu'ils essuient la table d'à côté autour de nous. Puis on a dîné. Puis on a marché. Tu as dit que tu n'étais pas fatiguée. Je ne l'étais pas non plus. On a rendu la ville plus petite cette nuit-là.",
        favorite: true),
  .init(id: "m04", year: 2022, date: "Août 2022",         sortKey: "2022-08-20", chapterId: "beginning",
        title: "Je l'ai dit en premier", placeId: "home", peopleIds: ["you"], tags: ["premières fois"],
        body: "C'est sorti avant que je puisse décider si je devais le dire. Tu as ri — pas de moi, de soulagement — et tu l'as dit en retour. Je n'ai jamais été plus heureux d'avoir échoué à garder quelque chose pour moi.",
        favorite: false),
  .init(id: "m05", year: 2022, date: "17 septembre 2022", sortKey: "2022-09-17", chapterId: "falling",
        title: "Cent jours", placeId: "home", peopleIds: ["you"], tags: ["étapes"],
        body: "Je comptais, en secret. Tu comptais à voix haute. On a acheté un petit gâteau à la boulangerie du coin et on l'a mangé dans la boîte, avec deux cuillères, sur le sol de la cuisine.",
        favorite: false),
  .init(id: "m06", year: 2022, date: "Novembre 2022",     sortKey: "2022-11-04", chapterId: "falling",
        title: "Sous la pluie", placeId: "home", peopleIds: ["you"], tags: ["ordinaire"],
        body: "On s'est abrités sous un auvent et on a attendu. Vingt minutes. Peut-être plus. Tu as posé ta tête sur mon épaule et je crois que c'est la première fois que je me suis senti complètement calme.",
        favorite: true),
  .init(id: "m07", year: 2022, date: "31 décembre 2022",  sortKey: "2022-12-31", chapterId: "falling",
        title: "Notre premier nouvel an", placeId: "home", peopleIds: ["you"], tags: ["étapes"],
        body: "Des feux d'artifice trop bruyants pour s'entendre. Alors tu l'as écrit sur ma paume avec ton doigt : l'année prochaine. Je savais ce que tu voulais dire. J'ai fermé ma main pour le garder.",
        favorite: false),
  .init(id: "m08", year: 2023, date: "14 février 2023",   sortKey: "2023-02-14", chapterId: "falling",
        title: "Malade pour la Saint-Valentin", placeId: "home", peopleIds: ["you"], tags: ["ordinaire","étapes"],
        body: "Tu avais 38,5 de fièvre. J'ai acheté de la soupe et le mauvais médicament et on a regardé le même film deux fois. Tu as dit que c'était la meilleure Saint-Valentin. Je crois que tu le pensais.",
        favorite: false),
  .init(id: "m09", year: 2023, date: "Avril 2023",        sortKey: "2023-04-22", chapterId: "falling",
        title: "Đà Lạt", placeId: "dalat", peopleIds: ["you"], tags: ["voyage","premières fois"],
        body: "Des pins et de la brume. Tu portais ma veste parce que tu avais oublié la tienne. On a roulé sur un scooter emprunté, lentement, mal. Un chien nous a suivis pendant un pâté de maisons et tu voulais le ramener à la maison. J'ai presque dit oui.",
        favorite: true),
  .init(id: "m10", year: 2023, date: "9 juin 2023",       sortKey: "2023-06-09", chapterId: "building",
        title: "Un an", placeId: "home", peopleIds: ["you"], tags: ["anniversaire","étapes"],
        body: "Année une. On a fait une liste de tout ce qu'on avait fait — des petites choses, surtout. La liste était plus longue que je ne le pensais. Tu as ajouté « et on est toujours là » en bas, et tu l'as souligné.",
        favorite: true),
  .init(id: "m11", year: 2023, date: "Septembre 2023",    sortKey: "2023-09-10", chapterId: "building",
        title: "Dîner chez tes parents", placeId: "parents", peopleIds: ["you","yourmom","yourdad"], tags: ["famille","premières fois"],
        body: "Ta mère n'arrêtait pas de remplir mon bol. Ton père m'a posé des questions sur mon travail et a vraiment écouté les réponses. Sur le chemin du retour, tu as dit « je crois qu'ils t'ont apprécié », et j'ai presque pleuré dans le taxi.",
        favorite: false),
  .init(id: "m12", year: 2023, date: "Décembre 2023",     sortKey: "2023-12-08", chapterId: "building",
        title: "Deux clés", placeId: "apt", peopleIds: ["you"], tags: ["chez nous","étapes"],
        body: "Deux clés. Une pour moi. La cuisine sentait encore la peinture quand on a mangé le premier dîner là-bas, assis par terre parce que la table n'était pas encore arrivée. On était si fatigués. On était si heureux.",
        favorite: false),
  .init(id: "m13", year: 2024, date: "Avril 2024",        sortKey: "2024-04-03", chapterId: "building",
        title: "La dispute que je préférerais oublier", placeId: "apt", peopleIds: ["you"], tags: ["difficile"],
        body: "Je n'écrirai pas tout. Seulement ceci : on a trouvé une solution. Ça a pris trois jours et beaucoup de plafonds fixés. On n'était pas pareils après. On était meilleurs.",
        favorite: false),
  .init(id: "m14", year: 2024, date: "9 juin 2024",       sortKey: "2024-06-09", chapterId: "staying",
        title: "Deux ans", placeId: "home", peopleIds: ["you"], tags: ["anniversaire","étapes"],
        body: "Tu as dit « on est vieux maintenant ». J'ai dit « on commence à peine ». Les deux vrais. On s'est acheté des fleurs à nous-mêmes. Elles ont tenu neuf jours.",
        favorite: false),
  .init(id: "m15", year: 2024, date: "Octobre 2024",      sortKey: "2024-10-14", chapterId: "staying",
        title: "Hội An, les lanternes", placeId: "hoian", peopleIds: ["you"], tags: ["voyage"],
        body: "Des lanternes sur la rivière. Tu en as acheté une et tu l'as mal allumée. On l'a regardée dériver peut-être dix mètres et puis couler. On a ri jusqu'à ne plus pouvoir.",
        favorite: true),
  .init(id: "m16", year: 2025, date: "Février 2025",      sortKey: "2025-02-09", chapterId: "staying",
        title: "Les semaines silencieuses", placeId: "apt", peopleIds: ["you"], tags: ["difficile"],
        body: "Le travail était dur. Tu étais fatiguée. J'ai fait trop de café et pas assez de conversation. Tu es rentrée un vendredi et tu as dit « tu m'as manqué » et on a recommencé. C'est toute l'entrée.",
        favorite: false),
  .init(id: "m17", year: 2025, date: "9 juin 2025",       sortKey: "2025-06-09", chapterId: "now",
        title: "Trois ans", placeId: "cafe", peopleIds: ["you"], tags: ["anniversaire","étapes"],
        body: "On n'a rien fait de spécial. On est allés au même café. On a commandé le même café. On s'est assis là où on s'est assis la première fois et on n'a pas eu besoin de dire grand-chose. Trois ans et on se dit encore des choses qu'on n'a dites à personne d'autre.",
        favorite: true),
  .init(id: "m18", year: 2025, date: "Décembre 2025",     sortKey: "2025-12-20", chapterId: "now",
        title: "Habitudes d'hiver", placeId: "apt", peopleIds: ["you"], tags: ["ordinaire"],
        body: "Deux tasses dans l'évier chaque matin. Tes pantoufles près de la porte. La façon dont la lumière entre par la fenêtre de la cuisine à 16 h et atterrit sur le même carré de plancher. Rien de tout cela n'est intéressant. Tout cela est tout.",
        favorite: false),
  .init(id: "m19", year: 2026, date: "Avril 2026",        sortKey: "2026-04-11", chapterId: "now",
        title: "Presque quatre", placeId: "home", peopleIds: ["you","friend"], tags: ["étapes"],
        body: "On a parlé de l'avenir comme si c'était un vrai endroit où on pourrait aller. On n'a rien décidé. On n'avait pas besoin. Plus tard, mon plus vieil ami m'a demandé comment ça allait. J'ai dit : toujours bien. Toujours surprenant. Toujours bien.",
        favorite: false),
  .init(id: "m20", year: 2026, date: "Aujourd'hui",       sortKey: "2026-05-24", chapterId: "now",
        title: "Aujourd'hui", placeId: "apt", peopleIds: ["you"], tags: ["ordinaire"],
        body: "Tu es dans la pièce d'à côté. Je t'entends taper. J'écris ceci pour me souvenir — pas des grandes choses, des petites. Le son de toi, à l'instant, dans la pièce d'à côté.",
        favorite: true),
]

let frLetters: [Letter] = [
  .init(id: "l01", date: "8 juillet 2022", occasion: "un mois",
        salutation: "Mon cher toi,",
        body: "Trente jours. Je n'arrête pas de me dire que ce n'est rien — et aussi que c'est le plus longtemps que je me suis senti moi-même depuis longtemps.\n\nTu me ralentis dans le bon sens. J'ai remarqué les arbres en marchant ce matin. J'ai remarqué la lumière. J'ai remarqué que je suis heureux d'une manière que j'avais cessé d'espérer.\n\nJe n'ai pas de question. Je n'ai pas de but. Je voulais juste l'écrire pour que plus tard, quand la vie devient bruyante, je puisse y revenir et me souvenir que tout a commencé aussi calmement.",
        signature: "À toi,", signedName: "moi"),
  .init(id: "l02", date: "25 décembre 2022", occasion: "notre premier Noël",
        salutation: "À la pièce la plus chaude de la maison,",
        body: "Six mois. Le sapin penche légèrement vers la gauche. C'est toi qui l'as installé. On m'a dit de ne pas le redresser.\n\nTu m'as fait quelque chose aujourd'hui que tu disais sans importance et évidemment ça l'est. Je le garde pour toujours, au cas où ce n'était pas clair.\n\nSi jamais j'oublie de te le dire à voix haute : merci d'être patiente avec moi. Merci de ne pas m'en vouloir de prendre du temps à dire ce que je pense. Merci d'attendre.",
        signature: "Toujours,", signedName: "moi"),
  .init(id: "l03", date: "9 juin 2023", occasion: "an un",
        salutation: "Pour notre première année,",
        body: "J'ai fait une liste ce matin de toutes les petites choses — ton rire quand tu es surprise, ta façon de lire les menus à voix haute, les mauvaises blagues que tu assumes. La liste était plus longue que je ne le pensais.\n\nJe pensais qu'une année ressemblerait à un cap. Au lieu de ça, ça ressemble au début de quelque chose que j'aimerais continuer aussi longtemps que je peux.\n\nJe ne suis pas très doué pour me souvenir de dire les choses importantes le jour où elles sont importantes. Alors je le dis maintenant, chaque jour, par écrit : je t'aime. Année une. Encore beaucoup, s'il te plaît.",
        signature: "Tout moi,", signedName: "moi"),
  .init(id: "l04", date: "6 avril 2024", occasion: "après une semaine difficile",
        salutation: "Toi,",
        body: "J'essaie d'écrire ça depuis deux jours. Je commence et j'arrête.\n\nVoilà ce que je veux dire : je suis désolé. Je suis aussi fier de nous. On n'a pas prétendu que ça n'était pas arrivé. On n'a pas prétendu qu'on ne le pensait pas. On y est restés et on a trouvé une solution.\n\nJe t'aime plus après qu'avant. Ça me surprend. J'espère que ça ne te surprend pas.",
        signature: "À toi, même fatigué,", signedName: "moi"),
  .init(id: "l05", date: "12 janvier 2025", occasion: "un dimanche tranquille",
        salutation: "Un matin tranquille,",
        body: "Il ne s'est rien passé aujourd'hui.\n\nTu as fait la grasse matinée. J'ai fait du café mal et je t'en ai apporté une tasse quand même. Tu as plissé les yeux dans la lumière et tu as dit bonjour de la voix que tu n'utilises que le matin.\n\nJ'écris ceci parce qu'il y aura des jours où j'oublierai à quoi ressemble l'ordinaire, et je veux me souvenir qu'ordinaire, avec toi, c'est ce que je veux le plus.",
        signature: "Toujours ton matin,", signedName: "moi"),
  .init(id: "l06", date: "9 juin 2025", occasion: "an trois",
        salutation: "Trois ans déjà,",
        body: "On est allés au même café. Tu portais les mauvaises chaussures pour la pluie et tu t'en fichais. On est restés longtemps sans dire grand-chose.\n\nJe sais ce que j'ai. Je n'ai pas fini d'en être surpris.\n\nVoici la vérité après trois ans : la plupart du travail c'est juste se présenter, et la plupart de la joie aussi. Tu te présentes. J'essaie. L'année quatre sera la meilleure, parce que je vais le penser plus fort.",
        signature: "À toi, exprès,", signedName: "moi"),
]
